-- MySQL Script generated by MySQL Workbench
-- Wed Jun 10 19:09:10 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `eventos`.`ev_categorias_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`ev_categorias_eventos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_evento` INT(11) NOT NULL,
  `id_preco` INT(11) NULL DEFAULT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `vagas` INT(11) NULL DEFAULT NULL,
  `condicao` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`ev_credenciais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`ev_credenciais` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `token` VARCHAR(200) NULL DEFAULT NULL,
  `servico` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`ev_desconto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`ev_desconto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_evento` INT(11) NULL DEFAULT NULL,
  `ticket` VARCHAR(30) NOT NULL,
  `desconto` INT(11) NOT NULL,
  `quantidade` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eventos`.`ev_inscricoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`ev_inscricoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_evento` INT(11) NOT NULL,
  `id_pessoa` INT(11) NOT NULL,
  `id_preco` INT(11) NULL DEFAULT NULL,
  `id_categoria` INT(11) NULL DEFAULT NULL,
  `valor_inscricao` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_inscricao` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `pre_inscricao` TINYINT(4) NULL DEFAULT NULL,
  `confirmado` TINYINT(4) NULL DEFAULT NULL,
  `data_pagseguro` TIMESTAMP NULL DEFAULT NULL,
  `status_pagseguro` INT(11) NULL DEFAULT NULL,
  `data_pagamento` TIMESTAMP NULL DEFAULT NULL,
  `data_confirmacao` DATETIME NULL DEFAULT NULL,
  `valor_pago` DECIMAL(10,2) NULL DEFAULT NULL,
  `taxa_cobranca` DECIMAL(10,2) NULL DEFAULT NULL,
  `valor_liquido` DECIMAL(10,2) NULL DEFAULT NULL,
  `codigo_pagamento` VARCHAR(50) NULL DEFAULT NULL,
  `formapagamento_pagseguro` INT(11) NULL DEFAULT NULL,
  `presente` INT(11) NULL DEFAULT NULL,
  `status_gateway` INT NULL DEFAULT NULL,
  `forma_pagamento_gateway` INT NULL DEFAULT NULL,
  `codigo_gateway` VARCHAR(60) NULL DEFAULT NULL,
  `data_atualizacao_gateway` DATETIME NULL DEFAULT NULL,
  `vencido` TINYINT NULL DEFAULT NULL,
  `data_vencido` DATETIME NULL DEFAULT NULL,
  `data_cancelamento` DATETIME NULL DEFAULT NULL,
  `forma_pagamento` VARCHAR(45) NULL DEFAULT NULL,
  `id_situacao` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eventos`.`ev_integracoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`ev_integracoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  `url` VARCHAR(200) NULL DEFAULT NULL,
  `tipo` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`ev_locais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`ev_locais` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(80) NOT NULL,
  `endereco` TEXT NULL DEFAULT NULL,
  `telefone` VARCHAR(30) NULL DEFAULT NULL,
  `cidade` VARCHAR(40) NULL DEFAULT NULL,
  `site` VARCHAR(100) NULL DEFAULT NULL,
  `latitude` VARCHAR(20) NULL DEFAULT NULL,
  `longitude` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`ev_mensagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`ev_mensagens` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `indice` VARCHAR(100) NULL DEFAULT NULL,
  `chave` VARCHAR(100) NULL DEFAULT NULL,
  `mensagem` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `eventos`.`ev_organizadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`ev_organizadores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(50) NOT NULL,
  `titulo_menor` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  `pagseguro_email` VARCHAR(80) NULL DEFAULT NULL,
  `pagseguro_token` VARCHAR(150) NULL DEFAULT NULL,
  `sms_hoje` VARCHAR(150) NULL DEFAULT NULL,
  `email_semvagas` TEXT NULL DEFAULT NULL,
  `email_confirmacao` TEXT NULL DEFAULT NULL,
  `email_confirme_agora` TEXT NULL DEFAULT NULL,
  `inscricao_dados_conta` TEXT NULL DEFAULT NULL,
  `inscricao_locais_pagamento` TEXT NULL DEFAULT NULL,
  `descricao` TEXT NULL,
  `site` VARCHAR(150) NULL,
  `publico_alvo` TEXT NULL,
  `periodicidade` TEXT NULL,
  `telefone` VARCHAR(30) NULL,
  `ativo` TINYINT(1) NULL DEFAULT 0,
  `senha` VARCHAR(20) NULL,
  UNIQUE INDEX `orga_pk` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eventos`.`ev_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`ev_pessoas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(15) NULL DEFAULT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `celular` VARCHAR(20) NULL DEFAULT NULL,
  `end_cep` VARCHAR(10) NULL DEFAULT NULL,
  `end_logradouro` VARCHAR(100) NULL DEFAULT NULL,
  `end_numero` VARCHAR(30) NULL DEFAULT NULL,
  `end_complemento` VARCHAR(30) NULL DEFAULT NULL,
  `end_bairro` VARCHAR(30) NULL DEFAULT NULL,
  `end_cidade` VARCHAR(30) NULL DEFAULT NULL,
  `end_estado` VARCHAR(2) NULL DEFAULT NULL,
  `newsletter` TINYINT(4) NULL DEFAULT NULL,
  `extras` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eventos`.`ev_precos_eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`ev_precos_eventos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_evento` INT(11) NOT NULL,
  `titulo` VARCHAR(50) NULL DEFAULT NULL,
  `vagas` INT(11) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `encerrado` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `eventos`.`ev_visitante_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eventos`.`ev_visitante_evento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ip` VARCHAR(42) NULL DEFAULT NULL,
  `referer` VARCHAR(500) NULL DEFAULT NULL,
  `userAgent` VARCHAR(500) NULL DEFAULT NULL,
  `mobile` TINYINT(4) NULL DEFAULT NULL,
  `id_evento` INT(11) NULL DEFAULT NULL,
  `data_acesso` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
